install.packages("tidyverse")
install.packages("tidygraph")
install.packages("igraph")
install.packages("ggraph")
install.packages("rJava")
# install.packages("BiocManager")
# BiocManager::install("ChemmineOB", version = "3.8")
# BiocManager::install("ChemmineR", version = "3.8")
# BiocManager::install("fmcsR") 
source("https://bioconductor.org/biocLite.R")
biocLite("ChemmineOB")
biocLite("ChemmineR")
biocLite("fmcsR")
